
COMMON_CLOCKING_DIR := $(VERIF_COMMON_ROOT)/clocking
COMMON_CLOCKING_OBJS_DIR := ${COMMON_CLOCKING_DIR}/objs

COMMON_CLOCKING_INCS := -I${VERIF_COMMON_ROOT}/clocking/
COMMON_CLOCKING_SRCS := ${VERIF_COMMON_ROOT}/clocking/tbclock.cpp

COMMON_CLOCKING_OBJS += $(patsubst %.cpp, $(COMMON_CLOCKING_OBJS_DIR)/%.o, $(notdir $(COMMON_CLOCKING_SRCS)))

$(COMMON_CLOCKING_OBJS_DIR)/%.o: ${COMMON_CLOCKING_DIR}/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) ${INCS} $(COMMON_CLOCKING_INCS) -c $< -o $@
